import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import '../../node_modules/@fortawesome/fontawesome-free/css/all.min.css'
import { Toaster } from "@/components/ui/sonner";
import MyProvider from "@/myProvider/MyProvider";
import { CartProvider } from "@/context/cart.context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MyProvider>
          <CartProvider>

        <Toaster  position="top-center" expand={false} richColors   />

        <Navbar/>
        {children}
        </CartProvider>
        </MyProvider>
      </body>
    </html>
  );
}
